/**
 * `latticeag gateway service install|uninstall|status` (spec §6.2, §1.3).
 *
 * Embedded mode: manager file operations run locally (the same review and
 * journal rules apply — nothing is written before the exact rendered plan
 * is approved by digest or interactive confirmation). Supported managers:
 * systemd user units, launchd LaunchAgents, and an already-installed pm2.
 */
import { existsSync, mkdirSync, renameSync, writeFileSync, unlinkSync, copyFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import type { Command } from "commander";
import { Option } from "commander";
import { v2 } from "@latticeag/core";
import { addGlobalOptions } from "../../globals.js";
import { fail, writeJson } from "../../json-envelope.js";
import {
  addSocketOption,
  commandName,
  failControl,
  gatewayIdentity,
  globalsOf,
  planDigest,
  displayPlan,
  requireConfirmation,
  requireReviewedPlan,
  resolveClient,
  usageFail,
} from "../../gateway/common.js";
import { cliBinPath } from "../../gateway/client.js";

const { EXIT } = v2.protocol;
const { sha256Hex } = v2.crypto;

export type ManagerName = "systemd" | "launchd" | "pm2";

export interface ServiceUnitFile {
  path: string;
  content: string;
}

export interface ServicePlan {
  manager: ManagerName;
  instance: string;
  exec: string[];
  files: Array<{
    path: string;
    bytes: number;
    sha256: string;
    exists: boolean;
  }>;
  contents: Record<string, string>;
}

function whichSync(bin: string): boolean {
  const pathEnv = process.env.PATH ?? "";
  for (const dir of pathEnv.split(path.delimiter)) {
    if (dir && existsSync(path.join(dir, bin))) {
      return true;
    }
  }
  return false;
}

/** --manager auto: systemd user on Linux, launchd on macOS, existing pm2 elsewhere. */
export function resolveManager(raw: string | undefined, ctx: { json?: boolean; command: string }): ManagerName {
  const manager = raw ?? "auto";
  if (manager === "systemd" || manager === "launchd" || manager === "pm2") {
    return manager;
  }
  if (manager !== "auto") {
    usageFail(`unknown --manager ${manager}`, ctx);
  }
  if (process.platform === "linux") {
    return "systemd";
  }
  if (process.platform === "darwin") {
    return "launchd";
  }
  if (whichSync("pm2")) {
    return "pm2";
  }
  fail("no supported service manager found (systemd/launchd absent, pm2 not installed)", {
    json: ctx.json,
    command: ctx.command,
    code: "SERVICE_MANAGER_UNAVAILABLE",
    exitCode: EXIT.BUSY,
  });
}

function systemdUnit(instance: string, exec: string[]): ServiceUnitFile {
  const file = path.join(
    homedir(),
    ".config",
    "systemd",
    "user",
    `latticeag-gateway-${instance}.service`,
  );
  const content = [
    "[Unit]",
    `Description=LatticeAG gateway (${instance})`,
    "After=default.target",
    "",
    "[Service]",
    "Type=simple",
    `ExecStart=${exec.join(" ")}`,
    "Restart=on-failure",
    "UMask=0077",
    "",
    "[Install]",
    "WantedBy=default.target",
    "",
  ].join("\n");
  // Start limits live on the unit in current systemd; kept in [Unit] for
  // forward compatibility (older releases accept them in [Service]).
  const withLimits = content.replace(
    "[Service]",
    "StartLimitIntervalSec=60\nStartLimitBurst=5\n\n[Service]",
  );
  return { path: file, content: withLimits };
}

function launchdUnit(instance: string, exec: string[]): ServiceUnitFile {
  const file = path.join(
    homedir(),
    "Library",
    "LaunchAgents",
    `ai.latticeag.gateway.${instance}.plist`,
  );
  const args = exec.map((a) => `    <string>${a}</string>`).join("\n");
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>ai.latticeag.gateway.${instance}</string>
  <key>ProgramArguments</key>
  <array>
${args}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
</dict>
</plist>
`;
  return { path: file, content };
}

function pm2Unit(instance: string, argv: string[], stateDir: string): ServiceUnitFile {
  const file = path.join(stateDir, "service", "ecosystem.config.cjs");
  const [script, ...args] = argv;
  const content = `// Generated by latticeag gateway service install — one fork-mode
// instance, exponential backoff, absolute executable, no secret env.
module.exports = {
  apps: [
    {
      name: "latticeag-gateway-${instance}",
      script: ${JSON.stringify(script)},
      args: ${JSON.stringify(args)},
      interpreter: ${JSON.stringify(process.execPath)},
      exec_mode: "fork",
      instances: 1,
      exp_backoff_restart_delay: 100,
      env: {},
    },
  ],
};
`;
  return { path: file, content };
}

/** Render the exact §1.3 unit file plan for a manager. */
export function renderServicePlan(opts: {
  manager: ManagerName;
  instance: string;
  stateDir: string;
}): ServicePlan {
  const exec = [cliBinPath(), "gateway", "start", "--foreground"];
  const unit =
    opts.manager === "systemd"
      ? systemdUnit(opts.instance, [process.execPath, ...exec])
      : opts.manager === "launchd"
        ? launchdUnit(opts.instance, [process.execPath, ...exec])
        : pm2Unit(opts.instance, exec, opts.stateDir);
  const files = [
    {
      path: unit.path,
      bytes: Buffer.byteLength(unit.content),
      sha256: sha256Hex(unit.content),
      exists: existsSync(unit.path),
    },
  ];
  return {
    manager: opts.manager,
    instance: opts.instance,
    exec: [process.execPath, ...exec],
    files,
    contents: { [unit.path]: unit.content },
  };
}

function printPlan(plan: ServicePlan, digest: string, json: boolean, command: string): void {
  if (json) {
    writeJson(command, true, {
      manager: plan.manager,
      instance: plan.instance,
      exec: plan.exec,
      files: plan.files,
      review_digest: digest,
    });
    return;
  }
  process.stdout.write(`manager ${plan.manager}\ninstance ${plan.instance}\n`);
  process.stdout.write(`exec ${plan.exec.join(" ")}\n`);
  for (const f of plan.files) {
    process.stdout.write(
      `${f.exists ? "replace" : "write"} ${f.path} (${f.bytes} bytes, sha256:${f.sha256})\n`,
    );
    process.stdout.write(`${plan.contents[f.path]}\n`);
  }
  process.stdout.write(`review_digest ${digest}\n`);
}

function writePlan(plan: ServicePlan): void {
  for (const f of plan.files) {
    const content = plan.contents[f.path];
    if (content === undefined) {
      continue;
    }
    mkdirSync(path.dirname(f.path), { recursive: true, mode: 0o700 });
    if (existsSync(f.path)) {
      // Existing units are backed up before merge/replace (§1.3).
      copyFileSync(f.path, `${f.path}.bak`);
    }
    const tmp = `${f.path}.tmp-${process.pid}`;
    writeFileSync(tmp, content, { mode: 0o600 });
    renameSync(tmp, f.path);
  }
}

async function runInstall(
  opts: { manager?: string; dryRun?: boolean; yes?: boolean; reviewDigest?: string; socket?: string },
  command: Command,
): Promise<void> {
  const globals = globalsOf(command);
  const json = globals.json === true;
  const ctx = { json, command: commandName(command) };
  const manager = resolveManager(opts.manager, ctx);
  const identity = gatewayIdentity();
  const plan = renderServicePlan({
    manager,
    instance: identity.instance,
    stateDir: path.join(identity.configDir, ".latticeag"),
  });
  const digest = planDigest({
    method: "service.install",
    manager: plan.manager,
    instance: plan.instance,
    files: plan.files,
    contents: plan.contents,
  });
  printPlan(plan, digest, json, ctx.command);
  if (opts.dryRun === true) {
    return;
  }
  await requireReviewedPlan({
    yes: opts.yes,
    reviewDigest: opts.reviewDigest,
    digest,
    summary: `install ${manager} unit for instance ${identity.instance}`,
    json,
    command: ctx.command,
  });
  writePlan(plan);
  if (json) {
    writeJson(ctx.command, true, { installed: true, files: plan.files });
    return;
  }
  process.stdout.write(`installed ${manager} unit\n`);
  if (manager === "systemd") {
    process.stdout.write("next: systemctl --user daemon-reload && systemctl --user enable --now latticeag-gateway-" + identity.instance + "\n");
  } else if (manager === "launchd") {
    process.stdout.write(`next: launchctl bootstrap gui/$(id -u) ${plan.files[0]?.path ?? ""}\n`);
  } else {
    process.stdout.write(`next: pm2 start ${plan.files[0]?.path ?? "ecosystem.config.cjs"} && pm2 save\n`);
  }
}

async function runUninstall(
  opts: { manager?: string; keepRunning?: boolean; yes?: boolean; socket?: string },
  command: Command,
): Promise<void> {
  const globals = globalsOf(command);
  const json = globals.json === true;
  const ctx = { json, command: commandName(command) };
  const manager = resolveManager(opts.manager, ctx);
  const identity = gatewayIdentity();
  const plan = renderServicePlan({
    manager,
    instance: identity.instance,
    stateDir: path.join(identity.configDir, ".latticeag"),
  });
  const target = plan.files[0];
  if (!target || !existsSync(target.path)) {
    fail(`no ${manager} unit installed at ${target?.path ?? "unknown path"}`, {
      json,
      command: ctx.command,
      code: "NOT_FOUND",
      exitCode: EXIT.GENERAL,
    });
  }
  await requireConfirmation({
    yes: opts.yes,
    summary: `remove ${manager} unit ${target.path} (data is preserved)`,
    json,
    command: ctx.command,
  });
  unlinkSync(target.path);
  let stopped: string | null = null;
  if (opts.keepRunning !== true) {
    // Best-effort graceful stop; never fails the uninstall.
    try {
      const { client } = resolveClient({ socket: opts.socket });
      const res = await client.call<{ state: string }>("daemon.stop", {
        grace_ms: 10000,
      });
      stopped = res.state;
    } catch {
      stopped = null;
    }
  }
  if (json) {
    writeJson(ctx.command, true, {
      removed: target.path,
      daemon_stop: stopped,
    });
    return;
  }
  process.stdout.write(`removed ${target.path}\n`);
}

async function runServiceStatus(
  opts: { manager?: string; socket?: string },
  command: Command,
): Promise<void> {
  const globals = globalsOf(command);
  const json = globals.json === true;
  const ctx = { json, command: commandName(command) };
  const manager = resolveManager(opts.manager, ctx);
  const identity = gatewayIdentity();
  const plan = renderServicePlan({
    manager,
    instance: identity.instance,
    stateDir: path.join(identity.configDir, ".latticeag"),
  });
  const unitPath = plan.files[0]?.path ?? null;
  const installed = unitPath !== null && existsSync(unitPath);

  // Manager state and process readiness are reported independently (§6.2).
  let processState: string = "unreachable";
  try {
    const { client } = resolveClient({ socket: opts.socket });
    const status = await client.call<v2.protocol.DaemonStatusResult>(
      "daemon.status",
      {},
    );
    processState = status.state;
  } catch (err) {
    void err;
    processState = "unreachable";
  }

  const data = {
    manager,
    unit_path: unitPath,
    installed,
    process_state: processState,
  };
  if (json) {
    writeJson(ctx.command, true, data);
    return;
  }
  process.stdout.write(
    `manager ${manager}\nunit ${unitPath ?? "-"}\ninstalled ${installed}\nprocess ${processState}\n`,
  );
}

export function registerServiceCommands(gateway: Command): Command {
  const service = gateway
    .command("service")
    .description("Install/manage the gateway as a user service.");

  const install = service
    .command("install")
    .description("Render, review, and install a service-manager unit.")
    .addOption(
      new Option("--manager <auto|systemd|launchd|pm2>", "Service manager").choices([
        "auto",
        "systemd",
        "launchd",
        "pm2",
      ]),
    )
    .option("--dry-run", "Print the exact file plan; write nothing")
    .option("--yes", "Approve the displayed plan")
    .option("--review-digest <hash>", "Digest of the displayed plan")
    .action(async (opts, command: Command) => {
      await runInstall(opts, command);
    });
  addGlobalOptions(install);
  addSocketOption(install);

  const uninstall = service
    .command("uninstall")
    .description("Remove the reviewed unit only; data is preserved.")
    .addOption(
      new Option("--manager <manager>", "Service manager").choices([
        "auto",
        "systemd",
        "launchd",
        "pm2",
      ]),
    )
    .option("--keep-running", "Do not stop a running daemon")
    .option("--yes", "Confirm removal")
    .action(async (opts, command: Command) => {
      await runUninstall(opts, command);
    });
  addGlobalOptions(uninstall);
  addSocketOption(uninstall);

  const status = service
    .command("status")
    .description("Report manager install state and process readiness.")
    .addOption(
      new Option("--manager <auto|systemd|launchd|pm2>", "Service manager").choices([
        "auto",
        "systemd",
        "launchd",
        "pm2",
      ]),
    )
    .action(async (opts, command: Command) => {
      await runServiceStatus(opts, command);
    });
  addGlobalOptions(status);
  addSocketOption(status);

  return service;
}
